"""empty message

Revision ID: 2978964ad306
Revises: 5f85ab46184e
Create Date: 2024-07-26 17:49:45.852825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2978964ad306'
down_revision = '5f85ab46184e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False))
        batch_op.add_column(sa.Column('order_status', sa.Enum('RECIBIDO', 'PREPARACION', 'ENVIADO', 'ENTREGADO', name='orderstatus'), nullable=False))
        batch_op.drop_constraint('order_orderStatus_key', type_='unique')
        batch_op.drop_constraint('order_totalAmount_key', type_='unique')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.drop_column('is_active')
        batch_op.drop_column('totalAmount')
        batch_op.drop_column('orderStatus')

    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('product_id', sa.Integer(), nullable=False))
        batch_op.alter_column('quantity',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.drop_constraint('order_items_ProductsId_key', type_='unique')
        batch_op.drop_constraint('order_items_orderId_key', type_='unique')
        batch_op.drop_constraint('order_items_quantity_key', type_='unique')
        batch_op.create_foreign_key(None, 'order', ['order_id'], ['id'])
        batch_op.create_foreign_key(None, 'product', ['product_id'], ['id'])
        batch_op.drop_column('is_active')
        batch_op.drop_column('orderId')
        batch_op.drop_column('ProductsId')

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(length=500), nullable=False))
        batch_op.alter_column('price',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.Enum('PERROS', 'GATOS', 'ROEDORES', 'PECES', 'PAJAROS', name='category'),
               existing_nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=500),
               existing_nullable=False)
        batch_op.drop_constraint('product_category_key', type_='unique')
        batch_op.drop_constraint('product_name_key', type_='unique')
        batch_op.drop_constraint('product_price_key', type_='unique')
        batch_op.drop_column('is_active')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('address',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=40),
               existing_nullable=False)
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=20),
               existing_nullable=False)
        batch_op.drop_constraint('user_address_key', type_='unique')
        batch_op.drop_constraint('user_name_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint('user_name_key', ['name'])
        batch_op.create_unique_constraint('user_address_key', ['address'])
        batch_op.alter_column('password',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.String(length=40),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)
        batch_op.alter_column('address',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.create_unique_constraint('product_price_key', ['price'])
        batch_op.create_unique_constraint('product_name_key', ['name'])
        batch_op.create_unique_constraint('product_category_key', ['category'])
        batch_op.alter_column('description',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)
        batch_op.alter_column('category',
               existing_type=sa.Enum('PERROS', 'GATOS', 'ROEDORES', 'PECES', 'PAJAROS', name='category'),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)
        batch_op.alter_column('price',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.drop_column('image')

    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ProductsId', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('orderId', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_unique_constraint('order_items_quantity_key', ['quantity'])
        batch_op.create_unique_constraint('order_items_orderId_key', ['orderId'])
        batch_op.create_unique_constraint('order_items_ProductsId_key', ['ProductsId'])
        batch_op.alter_column('quantity',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)
        batch_op.drop_column('product_id')
        batch_op.drop_column('order_id')

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('orderStatus', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('totalAmount', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_unique_constraint('order_totalAmount_key', ['totalAmount'])
        batch_op.create_unique_constraint('order_orderStatus_key', ['orderStatus'])
        batch_op.drop_column('order_status')
        batch_op.drop_column('total_amount')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
